### ISSUE TITLE
Add tests to the MMIO module

### ISSUE THREAD

**Issue by powerslider** [Consensys/linea-tracer#350]
- should be tested together with the MMU

**Comment by powerslider** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Linea-Arithmetization-6502cfb17907f98e3261c5e3/issues/Consensys/besu-sequencer-plugins/350?planning-poker) with Zenhub @letypequividelespoubelles

**Comment by OlivierBBB** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Linea-Arithmetization-6502cfb17907f98e3261c5e3/issues/Consensys/besu-sequencer-plugins/350?planning-poker) with Zenhub @OlivierBBB

**Comment by powerslider** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Linea-Arithmetization-6502cfb17907f98e3261c5e3/issues/Consensys/besu-sequencer-plugins/350?planning-poker) with Zenhub @powerslider

**Comment by powerslider** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Linea-Arithmetization-6502cfb17907f98e3261c5e3/issues/Consensys/besu-sequencer-plugins/350?planning-poker) with Zenhub @lorenzogentile404
