### ISSUE TITLE
Besu ↔ Geth line count

### ISSUE THREAD

**Issue by delehef** [Consensys/linea-tracer#467]
|Limit|Besu `?` Geth|Status|
|-|-|-|
|ADD|=||
|BIN|=||
|EXT|=||
|HUB|=||
|MOD| >||
|MMU|×| ignore|
|MUL|=||
|MXP|=||
|PUB_LOG|×||
|PUB_LOG_INFO|>||
|RLP_ADDR|>||
|RLP_TXN|×||
|RLP_TXRCPT|×||
|ROM|×|only proving a fake ROM|
|ROM_LEX|×||
|SHF|=||
|TRM|×||
|TXN_DATA|×||
|WCP|>||
|BLOCK_TX|=||
|PRECOMPILE_*|=||
|PRECOMPILE_ECPAIRING_WEIGHTED|×||
|L1 limits|×|ignore|

**Comment by jonesho** [comment]
Thanks for putting this as the consolidated table, much easier to communicate now!

@delehef few questions on this table:

- `RLP_ADDR` should map to geth `RLP` with larger value? why don't we call it `RLP` in besu instead?
- I never seen `MMIO` from besu trace counts, do we need to even mention it here?

**Comment by jonesho** [comment]
Current PR to keep track of the changes: https://github.com/Consensys/besu-sequencer-plugins/pull/459

**Comment by letypequividelespoubelles** [comment]
@delehef could add `STP`, traced in besu, not geth

**Comment by jonesho** [comment]
@delehef just added MMU in the table as its in the Besu response but not comparable to the geth counterpart, e.g. 10 vs 153 for block `352020` in testnet

**Comment by jonesho** [comment]
@delehef why did we remove MMU in the table, can you add it back with current status?
