### ISSUE TITLE
get PUB_LOG_INFO count close to geth count

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/linea-tracer#491]
PUB_LOG_INFO is significantly bigger in Besu, try to make it closer to Geth counting by testing returning 1 line count for all type of logs.

It should still be greater except for reverts that are wrongly counted in Geth.

**Comment by FlorianHuc** [comment]
a block for which it is smaller:

BLOCK 2006233-0x85ba90b417a1db135b5cda141c2cafa998a3759db0608f995ce40ed8a9bb9294 DIFFERED | PUB_LOG_INFO  | EXT: 9 = 9 | ADD: 29762 = 29762 | MXP: 9014 = 9014 | WCP: 4929 = 4929 | PRECOMPILE_ECMUL: 0 = 0 | BLOCK_L2L1LOGS: 0 = 0 | BLOCK_L1SIZE: 5895 vs 675 | SHF: 2096 = 2096 | HUB: 30339 = 30339 | EC_DATA: 20 = 20 | PRECOMPILE_ECPAIRING: 0 = 0 | PRECOMPILE_MODEXP: 0 = 0 | BLOCK_TX: 1 = 1 | MOD: 96 = 96 | MUL: 343 = 343 | PRECOMPILE_ECADD: 0 = 0 | BIN: 8400 = 8400 | PRECOMPILE_ECRECOVER: 1 = 1 | QUOTIENT_RLP_ADDR: 1.125 | RLP_ADDR: 9 vs 8 | QUOTIENT_ROM: 2.8304094961147923 | ROM: 118747 vs 41954 | PRECOMPILE_SHA2: 0 = 0 | PRECOMPILE_BLAKE2F: 0 = 0 | PUB_LOG_INFO: 6 < 12 | PRECOMPILE_RIPEMD: 0 = 0

revert?

**Comment by FlorianHuc** [comment]
BLOCK 1511803-0x20f618c7186587b09e2b700a7980b240b1e0ebaa8d643a1b4c3465f8adb0ebb4 DIFFERED: PUB_LOG_IN
[1511803-0x20f618c7186587b09e2b700a7980b240b1e0ebaa8d643a1b4c3465f8adb0ebb4.json.gz](https://github.com/Consensys/besu-sequencer-plugins/files/13700671/1511803-0x20f618c7186587b09e2b700a7980b240b1e0ebaa8d643a1b4c3465f8adb0ebb4.json.gz)
FO: 10 < 16

**Comment by letypequividelespoubelles** [comment]
can we close it @FlorianHuc ?
